/*----------------------------------------------------
OUTPUT FUNCTION DECLARATIONS
-----------------------------------------------------*/
extern void New_Watch_O_display(void*, DISPLAY_TYPE);
extern void New_Watch_O_beep(void*, _integer);

/*----------------------------------------------------
EXTERNAL FUNCTION DECLARATIONS
-----------------------------------------------------*/

extern void LABELS(
   LABELS_TYPE*, _boolean, _boolean, _boolean, _boolean, _boolean
);
extern void WATCH_TO_DISPLAY_POS(DISPLAY_POSITION*, WATCH_TIME_POSITION);
extern void ALARM_TO_DISPLAY_POS(DISPLAY_POSITION*, ALARM_TIME_POSITION);
extern void STATUS(
   STATUS_TYPE*, _boolean, _boolean, _boolean, _boolean
);
extern void MAKE_DISPLAY(
   DISPLAY_TYPE*, MAIN_DISPLAY_TYPE, MINI_DISPLAY_TYPE,
   string, STATUS_TYPE, DISPLAY_POSITION, LABELS_TYPE
);
extern void WATCH_TIME_TO_MAIN_DISPLAY(MAIN_DISPLAY_TYPE*, WATCH_TIME_TYPE);
extern void STOPWATCH_TIME_TO_MAIN_DISPLAY(
   MAIN_DISPLAY_TYPE*, STOPWATCH_TIME_TYPE
);
extern void ALARM_TIME_TO_MAIN_DISPLAY(MAIN_DISPLAY_TYPE*, ALARM_TIME_TYPE);
extern void WATCH_DATE_TO_MINI_DISPLAY(MINI_DISPLAY_TYPE*, WATCH_TIME_TYPE);
extern void WATCH_TIME_TO_MINI_DISPLAY(MINI_DISPLAY_TYPE*, WATCH_TIME_TYPE);
extern void WATCH_DAY_TO_ALPHA_DISPLAY(string*, WATCH_TIME_TYPE);
extern void TOGGLE_24H_IN_ALARM_MODE(ALARM_TIME_TYPE*, ALARM_TIME_TYPE);
extern void SET_ALARM_TIME(
   ALARM_TIME_TYPE*, ALARM_TIME_TYPE, ALARM_TIME_POSITION
);
extern void NEXT_ALARM_TIME_POSITION(
   ALARM_TIME_POSITION*, ALARM_TIME_POSITION
);
extern void COMPARE_WATCH_ALARM_TIME(
   _boolean*, WATCH_TIME_TYPE, ALARM_TIME_TYPE
);
extern void INCREMENT_WATCH_TIME(WATCH_TIME_TYPE*, WATCH_TIME_TYPE);
extern void TOGGLE_24H_IN_WATCH_MODE(WATCH_TIME_TYPE*, WATCH_TIME_TYPE);
extern void CONFIRM_TIME(WATCH_TIME_TYPE*, WATCH_TIME_TYPE);
extern void INCREMENT_WATCH_TIME_IN_SET_MODE(
   WATCH_TIME_TYPE*, WATCH_TIME_TYPE , WATCH_TIME_POSITION
);
extern void NEXT_WATCH_TIME_POSITION(
   WATCH_TIME_POSITION*, WATCH_TIME_POSITION
);
extern void SET_WATCH_TIME(
   WATCH_TIME_TYPE*, WATCH_TIME_TYPE, WATCH_TIME_POSITION
);
extern void IS_O_CLOCK(_boolean*, WATCH_TIME_TYPE);
extern void INCREMENT_STOPWATCH_TIME(
   STOPWATCH_TIME_TYPE*, STOPWATCH_TIME_TYPE
);
extern void IS_ZERO_MOD_10_MN(_boolean*, STOPWATCH_TIME_TYPE);

